version: "3.8"

services:
    db:
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: example
            MYSQL_DATABASE: example
        volumes:
            - data:/var/lib/mysql
        ports:
            - 33061:3306

    phpmyadmin:
        image: phpmyadmin:latest
        ports:
            - 3110:80
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: example
        depends_on:
            - db
        volumes:
            - phpmyadmin:/sessions

# volumes
volumes:
    data:
    phpmyadmin:
